=== llka/XML/data/Catalogue.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema     xmlns:xs="http://www.w3.org/2001/XMLSchema"
               targetNamespace="http://www.example.com/papers"
               xmlns="http://www.example.com/papers">

  <xs:element name="publication" type="PublicationType" abstract="true"></xs:element>

  <xs:element name="newspaper" type="NewspaperType" substitutionGroup="publication"></xs:element>

  <xs:element name="magazine" type="MagazineType" substitutionGroup="publication"></xs:element>

  <xs:element name="papers">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="publication" minOccurs="1" maxOccurs="unbounded"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>

	<xs:complexType name="PublicationType">
      <xs:sequence>
        <xs:element name="period" type="Period"></xs:element>
        <xs:element name="pages" type="xs:int"></xs:element>
        <xs:element name="color" type="Color" default="blackAndWhite"></xs:element>
        <xs:element name="issn" type="ISSN"></xs:element>
        <xs:element name="number" type="Number"></xs:element>
      </xs:sequence>
      <xs:attribute name="title" type="xs:string" use="required"/>
      <xs:attribute name="topic" use="optional" default="SPORTS">
        <xs:simpleType>
          <xs:restriction base="xs:string">
            <xs:enumeration value="FASHION"></xs:enumeration>
            <xs:enumeration value="WILDLIFE"></xs:enumeration>
            <xs:enumeration value="RELIGION"></xs:enumeration>
            <xs:enumeration value="SPORTS"></xs:enumeration>
            <xs:enumeration value="SHOWBIZ"></xs:enumeration>
            <xs:enumeration value="COOKING"></xs:enumeration>
            <xs:enumeration value="CULTURE"></xs:enumeration>
            <xs:enumeration value="LITERATURE"></xs:enumeration>
            <xs:enumeration value="POLITICS"></xs:enumeration>
            <xs:enumeration value="EDUCATION"></xs:enumeration>
            <xs:enumeration value="CRIME"></xs:enumeration>
            <xs:enumeration value="SCIENCE"></xs:enumeration>
            <xs:enumeration value="AUTO"></xs:enumeration>
          </xs:restriction>
        </xs:simpleType>
      </xs:attribute>
	</xs:complexType>

  <xs:complexType name="NewspaperType">
    <xs:complexContent>
      <xs:extension base="PublicationType">
        <xs:sequence>
          <xs:element name="geographic" type="GeographicalScope" default="national"></xs:element>
          <xs:element name="index" type="xs:int"></xs:element>
        </xs:sequence>
      </xs:extension>
    </xs:complexContent>
  </xs:complexType>

  <xs:complexType name="MagazineType">
    <xs:complexContent>
      <xs:extension base="PublicationType">
        <xs:sequence>
          <xs:element name="paper" type="PaperType" default="matt"></xs:element>
          <xs:element name="cover" type="CoverType" default="paperBack"></xs:element>
        </xs:sequence>
      </xs:extension>
    </xs:complexContent>
  </xs:complexType>

  <xs:simpleType name="Period">
    <xs:restriction base="xs:string">
      <xs:enumeration value="daily"></xs:enumeration>
      <xs:enumeration value="weekly"></xs:enumeration>
      <xs:enumeration value="monthly"></xs:enumeration>
      <xs:enumeration value="twiceYearly"></xs:enumeration>
      <xs:enumeration value="yearly"></xs:enumeration>
    </xs:restriction>
  </xs:simpleType>

  <xs:simpleType name="Color">
    <xs:restriction base="xs:string">
      <xs:enumeration value="colored"></xs:enumeration>
      <xs:enumeration value="blackAndWhite"></xs:enumeration>
    </xs:restriction>
  </xs:simpleType>

  <xs:simpleType name="ISSN">
    <xs:restriction base="xs:ID">
      <xs:pattern value="([A-Z][0-9]{4})(-)([0-9]{4})"/>
    </xs:restriction>
  </xs:simpleType>

  <xs:complexType name="Number">
    <xs:sequence>
      <xs:element name="overall" type="xs:int" />
      <xs:element name="current" type="xs:int" />
    </xs:sequence>
  </xs:complexType>

  <xs:simpleType name="GeographicalScope">
    <xs:restriction base="xs:string">
      <xs:enumeration value="local"></xs:enumeration>
      <xs:enumeration value="national"></xs:enumeration>
      <xs:enumeration value="international"></xs:enumeration>
    </xs:restriction>
  </xs:simpleType>

  <xs:simpleType name="CoverType">
    <xs:restriction base="xs:string">
      <xs:enumeration value="hardBack"></xs:enumeration>
      <xs:enumeration value="paperBack"></xs:enumeration>
    </xs:restriction>
  </xs:simpleType>

  <xs:simpleType name="PaperType">
    <xs:restriction base="xs:string">
      <xs:enumeration value="matt"></xs:enumeration>
      <xs:enumeration value="glossy"></xs:enumeration>
    </xs:restriction>
  </xs:simpleType>

</xs:schema>

=== llka/XML/data/test.xml
<?xml version="1.0" encoding="UTF-8"?>
<papers 	xmlns="http://www.example.com/papers"
	 		xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	  		xsi:schemaLocation="http://www.example.com/papers Catalogue.xsd ">
	<newspaper title="1" topic="WILDLIFE">
		<period>daily</period>
		<pages>1</pages>
		<color>colored</color>
		<issn>O111-1111</issn>
		<number>
			<overall>1</overall>
			<current>1</current>
		</number>
		<geographic>international</geographic>
		<index>111111</index>
	</newspaper>

	<magazine title="2" topic="SPORTS">
		<period>monthly</period>
		<pages>1</pages>
		<color>colored</color>
		<issn>O111-2222</issn>
		<number>
			<overall>1</overall>
			<current>1</current>
		</number>
		<paper>glossy</paper>
		<cover>hardBack</cover>
	</magazine>

	<magazine title="3">
		<period>monthly</period>
		<pages>1</pages>
		<color>colored</color>
		<issn>O111-3333</issn>
		<number>
			<overall>1</overall>
			<current>1</current>
		</number>
		<paper>glossy</paper>
		<cover>hardBack</cover>
	</magazine>
</papers>

=== llka/XML/data/Catalogue.xml
<?xml version="1.0" encoding="UTF-8"?>
<papers 	xmlns="http://www.example.com/papers"
	 		xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	  		xsi:schemaLocation="http://www.example.com/papers Catalogue.xsd ">
	<newspaper title="Pressball" topic="SPORTS">
		<period>weekly</period>
		<pages>20</pages>
		<color>blackAndWhite</color>
		<issn>1111-3333</issn>
		<number>
			<overall>3991</overall>
			<current>5</current>
		</number>
		<geographic>local</geographic>
		<index>152073</index>
	</newspaper>

	<magazine title="EuroFutball" topic="SPORTS">
		<period>monthly</period>
		<pages>120</pages>
		<color>colored</color>
		<issn>1121-3333</issn>
		<number>
			<overall>114</overall>
			<current>2</current>
		</number>
		<paper>glossy</paper>
		<cover>hardBack</cover>
	</magazine>

	<magazine title= "Popular Mechanics" topic="SCIENCE">
		<period>monthly</period>
		<pages>125</pages>
		<color>colored</color>
		<issn>1131-3333</issn>
		<number>
			<overall>159</overall>
			<current>2</current>
		</number>
		<paper>matt</paper>
		<cover>paperBack</cover>
	</magazine>

	<magazine title= "All Football">
		<period>monthly</period>
		<pages>95</pages>
		<color>colored</color>
		<issn>1141-3333</issn>
		<number>
			<overall>74</overall>
			<current>1</current>
		</number>
		<paper>glossy</paper>
		<cover>paperBack</cover>
	</magazine>

	<magazine title= "Total Football">
		<period>monthly</period>
		<pages>140</pages>
		<color>colored</color>
		<issn>1151-3333</issn>
		<number>
			<overall>36</overall>
			<current>11</current>
		</number>
		<paper>glossy</paper>
		<cover>hardBack</cover>
	</magazine>

	<magazine title= "BASSMASTER" topic="WILDLIFE">
		<period>monthly</period>
		<pages>103</pages>
		<color>colored</color>
		<issn>1161-3333</issn>
		<number>
			<overall>104</overall>
			<current>1</current>
		</number>
		<paper>glossy</paper>
		<cover>paperBack</cover>
	</magazine>

	<magazine title="Top Gear" topic="AUTO">
		<period>monthly</period>
		<pages>140</pages>
		<color>colored</color>
		<issn>7111-3333</issn>
		<number>
			<overall>81</overall>
			<current>10</current>
		</number>
		<paper>glossy</paper>
		<cover>hardBack</cover>
	</magazine>

	<newspaper title="WORLD FISHING AND AQUACULTURE" topic="WILDLIFE">
		<period>weekly</period>
		<pages>32</pages>
		<color>colored</color>
		<issn>8113-9333</issn>
		<number>
			<overall>2712</overall>
			<current>2</current>
		</number>
		<geographic>international</geographic>
		<index>152474</index>
	</newspaper>

	<magazine title="Рыбачьте с нами" topic="WILDLIFE">
		<period>monthly</period>
		<pages>144</pages>
		<color>colored</color>
		<issn>9156-3333</issn>
		<number>
			<overall>187</overall>
			<current>2</current>
		</number>
		<paper>glossy</paper>
		<cover>hardBack</cover>
	</magazine>

	<magazine title= "Expert Fishing" topic="WILDLIFE">
		<period>monthly</period>
		<pages>80</pages>
		<color>colored</color>
		<issn>1026-3333</issn>
		<number>
			<overall>53</overall>
			<current>2</current>
		</number>
		<paper>matt</paper>
		<cover>paperBack</cover>
	</magazine>

	<newspaper title= "KP" topic="POLITICS">
		<period>daily</period>
		<pages>24</pages>
		<color>colored</color>
		<issn>1131-3378</issn>
		<number>
			<overall>7432</overall>
			<current>38</current>
		</number>
		<geographic>national</geographic>
		<index>152187</index>
	</newspaper>

	<magazine title= "Полымя" topic="LITERATURE">
		<period>twiceYearly</period>
		<pages>80</pages>
		<color>blackAndWhite</color>
		<issn>1226-3333</issn>
		<number>
			<overall>114</overall>
			<current>1</current>
		</number>
		<paper>matt</paper>
		<cover>paperBack</cover>
	</magazine>

	<newspaper title= "Наша нива" topic="LITERATURE">
		<period>weekly</period>
		<pages>20</pages>
		<color>blackAndWhite</color>
		<issn>1326-3333</issn>
		<number>
			<overall>1882</overall>
			<current>6</current>
		</number>
		<geographic>national</geographic>
		<index>153218</index>
	</newspaper>

	<magazine title= "Hot Rod Magazine" topic="AUTO">
		<period>monthly</period>
		<pages>100</pages>
		<color>colored</color>
		<issn>1421-3333</issn>
		<number>
			<overall>104</overall>
			<current>2</current>
		</number>
		<paper>matt</paper>
		<cover>hardBack</cover>
	</magazine>

	<magazine title= "Autoweek" topic="AUTO">
		<period>weekly</period>
		<pages>50</pages>
		<color>colored</color>
		<issn>1521-3333</issn>
		<number>
			<overall>164</overall>
			<current>6</current>
		</number>
		<paper>matt</paper>
		<cover>paperBack</cover>
	</magazine>

	<magazine title= "Classic Cars" topic="AUTO">
		<period>monthly</period>
		<pages>130</pages>
		<color>colored</color>
		<issn>1621-3333</issn>
		<number>
			<overall>344</overall>
			<current>2</current>
		</number>
		<paper>glossy</paper>
		<cover>hardBack</cover>
	</magazine>

</papers>
